### ISSUE TITLE
Improperly url-encoded filesystem names in ns5/nfs.py

### ISSUE THREAD

**Issue by peter-slovak** [Nexenta/cinder#197]
The `_get_share_datasets()` method returns an URL-encoded filesystem name (the second part of the return tuple), but its result is frequently treated as non-encoded in many other methods.

Please note that the buggy behavior only manifests itself when you use "URL-encodable" characters in filesystem names, e.g. in our case the pool name is "data" and  filesystem names are "dev/cinder" or "production/cinder". The slash in the filesystem name is the problematic char.

The first type of improper use is, for example, in `_do_create_volume()`. Here, the URL-encoded FS name is used in the `data` dictionary that is sent as JSON payload. Since there is no need to URL-encode a payload, the server reads the data as-is and fails with an error of type "Filesystem not found: data/dev%2Fcinder".

The other type of improper use is in `revert_to_snapshot()`. After we define the `fs` variable (e.g. "dev%2Fcinder"), it gets copied to `fs_path`. Afterwards, the `url` is constructed with this variable, albeit transformed with `urllib.parse.quote_plus(fs_path)`. This results in double-encoding the forward slash and again, an API error.

I think it would be beneficial to always treat the filesystem name as a plain string and then abstract embedding that into JSON data or into the URL in a more generic way.

**Comment by deiter** [comment]
Hello Peter!

Thank you for the detailed explanation! Please let me fix it.

**Comment by deiter** [comment]
Hello Peter,

Fixed by https://github.com/Nexenta/cinder/commit/47246c74a8a9c78e67e145e0b06d27f73526f140 for master branch. Please let me port this fix into another stable branches.

Thank you!

**Comment by peter-slovak** [comment]
Great, thank you for the fix and other improvements!

**Comment by deiter** [comment]
Hello Peter,

Fix has been merged:

* stable/rocky
* stable/queens
* stable/pike

Please let me know if you have any questions.

**Comment by peter-slovak** [comment]
Thank you! Unfortunately, we won't have the capacity to test the change for a few more weeks, but I think we can close this issue.
